### ISSUE TITLE
TODO: Documentations

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2-net-www#253]
Putting this here for future references.

- [x] Add more configuration stuff (e.g. controllers, etc).
- [x] Add more troubleshooting guide.
- [x] Check for unused link.
- [x] Rework the category.
- [x] Get better quality image.
- [x] Check Discord Embed preview of each page
- [x] Look around the PCSX2 wiki.
- [x] Port over some of hifumi's prompt to the docs.
- [x] Add building process for both Windows and Linux.
- [x] Add instructions to update GPU driver (and add links to the download too).

Minor changes/fixes:

- [x] Add macOS to system requirements.
- [x] Add more details and screenshots.

**Comment by Mrlinkwii** [comment]
re: Add building process for both Windows and Linux. ,

it would probably be better to just link the  github wiki pages of each subject
